### ISSUE TITLE
SelectPointsType

### ISSUE THREAD

**Issue by mamoun86** [creold/illustrator-scripts#1]
Select Points Type is not Working  ??
Adobe: CC 2020 , OS: windows 10 2004

Thanks

**Comment by creold** [comment]
Hi. The script works in CC 2020. You can record a video or GIF to demonstrate your problem?

**Comment by mamoun86** [comment]
[Uploading 2020-07-16_17-07-58-132.zip…]()

**Comment by mamoun86** [comment]
https://streamable.com/xo0scg

**Comment by creold** [comment]
Now I understand. The script worked correctly. In the upper example, you selected the corner points of two rectangles and the points of circles, so their script was not removed from the selection. The script is to remove only segments without points from the selection.

**Comment by mamoun86** [comment]
Ah, Thanks for issue but good nice
