### ISSUE TITLE
Artboards Finder v0.1.4 not zooming

### ISSUE THREAD

**Issue by daspiderboris** [creold/illustrator-scripts#10]
Hello Sergey,
Trying out the artboard finder script in illustrator 2023 (27.0.1), the script runs and is able to identify the artboard, change the number in the "artboard navigation" but does not actually zoom over to the artboard. I've tried changing the zoom ratio and that doesn't seem to do anything.

thank you for all of your work on these scripts!

**Comment by daspiderboris** [comment]
I did some additional testing and found the issue is only in one specific illustrator file at the moment. not sure what's different with that file and will try to pin point it.

**Comment by creold** [comment]
@daspiderboris could you please share this .ai file? Unless, of course, it contains confidential information.

**Comment by daspiderboris** [comment]
Thanks for following up... I don't think I can share that specific file. I haven't debugged illustrator scripts but will look into that or stripping the file down to remove any client content before sharing it.
