### ISSUE TITLE
BatchTrace Options

### ISSUE THREAD

**Issue by larssteenhoff** [creold/illustrator-scripts#13]
I would like to ask if you know if there is a way to export the traced results back to the original file ?  
for example if the input file was a .psd file make illustrator trace and save the results back to the .psd file. as bitmap not vector.

Is there a way to do this?

**Comment by creold** [comment]
It is possible. But write a separate export function for each input file extension. For example, if the input file is `name.jpg`, then the tracing result should be exported to `jpg` with a certain set of parameters. The API has its own methods for different raster formats.
