### ISSUE TITLE
Any chance of a Zoom and center sister script that only zooms and centers to the active artboard?

### ISSUE THREAD

**Issue by fmotion1** [creold/illustrator-scripts#14]
Illustrator has `Fit artboard in window` in the view menu, but it completely fills the screen at 100%. I really like how your `Zoom and Center` script has a ratio to reduce the zoom to a more sane size. But it only operates on everything visible. So if I have a lot of artwork (like a big icon grid), it just zooms to fit all the icons.

You would be my hero if you could put together a script that does the same as `Zoom and Center`, but for the active artboard.

And even more, if you're feeling ambitious, another that does the same for the current selection.

Really appreciate the consideration, and love your scripts. 

Thanks,
Jay

**Comment by creold** [comment]
Hi @fmotion1,
"...the same for the current selection" - but that's what the `Zoom and Center` script does. If you have something selected in your document, it will only zoom to those objects. Or when you select objects and run the script, do you not zoom in on them? The zoom factor from 0 to 1 changes in the script code in the variable `ratio`.
