### ISSUE TITLE
batch trace to svg

### ISSUE THREAD

**Issue by soans1994** [creold/illustrator-scripts#15]
hello,

I am interested in your batch trace script.
https://github.com/creold/illustrator-scripts/blob/master/md/Item.md#batchtrace
Is it possible to save all the output as vectorized svg files. 

Thank you

**Comment by creold** [comment]
Hi @soans1994 
1) Use the original BatchTrace to export traced images to separate files (uncheck `Vectorize in single file`).
2) Use `exportAiToSvg.jsx` (unzip archive) for re-save .ai files from folder to svg.
[exportAiToSvg.zip](https://github.com/creold/illustrator-scripts/files/11533219/exportAiToSvg.zip)

**Comment by soans1994** [comment]
thank you
