### ISSUE TITLE
Batch Tracing from Folder ignores preset

### ISSUE THREAD

**Issue by kendesign** [creold/illustrator-scripts#16]
First and foremost, I would like to thank you for your great work.

I have just spent hours trying to achieve batch processing with image tracing using Adobe tools, where I can choose my own preset, but to no avail. I also explored scripting, which was able to load my preset, but the number of colors was always set to 100, even though it is defined differently in the preset. In the end, I tried to define the parameters in the script itself, but I lost patience because the settings offer different possibilities and options than the sliders in Illustrator itself.

I was just about to go to bed when I found your scripts, which are brilliant. Unfortunately, there is a problem with batch processing from a folder where the selected tracing preset is being ignored. Everything works correctly with open files. I was also a bit confused because the script can only be opened when a file is open; otherwise, it does not respond.

Perhaps you have a solution to this problem or an idea of how to fix it?

Kind Regards

**Comment by creold** [comment]
@kendesign thanks for appreciating my scripts.
1) The scripting has the problem of defining a color limit that is different from the setting in the Image Trace panel.  The Adobe developers seem to have mixed up the attributes. I plan to document this problem in a future blog post.
2) "can only be opened when a file is open" — it's a bug, I'll fix it in the update. Thanks for the report.
3) "selected tracing preset is being ignored" — in my tests, the Trasing preset is applied to the images from the folder. I haven't seen it ignored. Can you capture video?

**Comment by kendesign** [comment]
Hey, sure: https://vimeo.com/833097003/224de91af7
Illustrator is up to date, 27.5.
It doesn't seem to recognize the preset at all.
![Bildschirmfoto 2023-06-04 um 20 23 41](https://github.com/creold/illustrator-scripts/assets/63106281/f2d6b178-b380-498b-90cc-02f9c09ab25c)

**Comment by creold** [comment]
@kendesign I have 27.5 installed and cannot reproduce this problem. Can you attach your test PNGs and your "Vectorizing Presets" file from `Users/[user name]/Library/Preferences/Adobe Illustrator 27/[language]/` in a zip archive?

**Comment by kendesign** [comment]
[26_05_23__-1_a_minimalist_unique_simple_iconic_flat_vector_mascot__16850982924559032.png.zip](https://github.com/creold/illustrator-scripts/files/11652979/26_05_23__-1_a_minimalist_unique_simple_iconic_flat_vector_mascot__16850982924559032.png.zip)

**Comment by kendesign** [comment]
:( that's really sad, at least i feel less stupid now. Thank you for trying to help!
Wich latest possible Version of Illustrator will do the trick?

**Comment by creold** [comment]
@kendesign this is simple: the scripting language from the preset in your example also loads the values Colors: 100 instead of 10, and what looks white to you is RGB 253,253,253, so Ignore White does not work. This is the same bug in Adobe's scripting language.
![white](https://github.com/creold/illustrator-scripts/assets/32217031/81456e76-5fa1-4f8f-9414-86e6d3dfcdd3)
