### ISSUE TITLE
Running SplitPath from an Action causes the script to not work correctly.

### ISSUE THREAD

**Issue by NicNamSam** [creold/illustrator-scripts#17]
If you attempt to run the SplitPath.jsx script from an Action (through the simple "Insert Menu Item..." option), the SplitPath UI will appear as normal, but when the OK button is pressed, the expected splitting of the paths doesn't happen, and instead the paths and shape are only grouped into a Live Paint group.

**Comment by creold** [comment]
Thanks for your report, in this case I found how to fix Live Paint expand and upload SplitPath v1.3

Running scripts through actions is always unpredictable. Adobe hasn't created a perfect mechanism. If you run a script through an action, but that script refers to another action (app.doScript(set, name)), you will even get a freeze in Adobe Illustrator.
