### ISSUE TITLE
MoveArtboards script leaves behind red text labels if you undo the script.

### ISSUE THREAD

**Issue by fmotion1** [creold/illustrator-scripts#18]
Take a look at the video:

https://github.com/creold/illustrator-scripts/assets/33441569/f921df99-2bf2-4c89-8d16-5798293d05ea

Not a huge deal, just letting you know about the bug. 👍

**Comment by creold** [comment]
@fmotion1 thank you. But it's not a bug. To show the artboard indexes, the script has to create a new layer with the texts and refresh the screen - Illustrator records this action in the document history. That's why you have to use double Ctrl+Z to undo the script.
