### ISSUE TITLE
[BatchRenamer] Renamer won't recognize text object default names

### ISSUE THREAD

**Issue by sermelipharo** [creold/illustrator-scripts#19]
Script doesn't recognize default names of text objects

**Description:**

When renaming a text object, its name is automatically inserted into the script. However, if the object's name is left as the default (i.e., it matches the text content of the object), the script ends up with an empty space, even when using the `{N}` placeholder.

**Steps to reproduce:**

1. Create a new text object with the default name (which matches its content).
2. Use the script to process the object.
3. Observe that where the object's name should appear, there is an empty space, even if `{N}` is used.

**Expected behavior:**
The script should be able to recognize and insert the default names of text objects

**Actual behavior:**
The script leaves an empty space in place of the object's name if the name is the default.

<img width="911" alt="image" src="https://github.com/creold/illustrator-scripts/assets/9950381/7db291d2-26dd-41d6-9ef2-dcc75ef28c2f">
<img width="856" alt="image" src="https://github.com/creold/illustrator-scripts/assets/9950381/5a7ecafa-ee25-4c75-aab3-b5aef6ee0b0f">

**Comment by sermelipharo** [comment]
I guess we need to add this somewhere in the script, but I don't know how well it will be working if text contains special symbols
```
    if (item.name == "" || item.name == item.contents) {
                item.name = item.contents;}
```

**Comment by creold** [comment]
@sermelipharo technically, this was not an error. Since the default name of a text frame does not exist in Illustrator, the Adobe SDK returns an empty string. But yes, we can force the content to be displayed as if it were a name.

Check the BatchRenamer update v.1.3.1.

**Comment by sermelipharo** [comment]
Thank you very much for this fix!
