### ISSUE TITLE
A bug was found in SelectBySwatches.jsx

### ISSUE THREAD

**Issue by jxyun99** [creold/illustrator-scripts#23]
A bug was found in SelectBySwatches.jsx. If the top-level layer of Illustrator is locked or hidden, running SelectBySwatches.jsx will cause Illustrator software to be unable to perform other operations and can only close Illustrator

**Comment by creold** [comment]
@jxyun99 tell me what version of Illustrator, PC or MacOS, how do you run the script? Maybe there is a screen record and a test file. Since I'm not getting this error.

**Comment by jxyun99** [comment]
PC Illustrator 2023 have bug ,but Illustrator CS6 is gold

**Comment by jxyun99** [comment]
![123](https://github.com/creold/illustrator-scripts/assets/61897787/dbaa8131-3aa0-44eb-8211-066f88b12c45)

**Comment by creold** [comment]
@jxyun99 oh, sh**, that's a nasty bug. It doesn't exist on Mac OS. As far as I know, the Select > Same > Fill (Stroke) Color command called in the script on the PC causes mouse problems if the top layer is hidden or locked. 

Check this hotfix
[SelectBySwatches.zip](https://github.com/creold/illustrator-scripts/files/15051698/SelectBySwatches.zip)

**Comment by jxyun99** [comment]
Now it's ready, thank you
