### ISSUE TITLE
Can you PLEASE create a script for:

### ISSUE THREAD

**Issue by defactofrank** [creold/illustrator-scripts#7]
#### **Example:**  (`` click to enlarge image ``)
<img src="https://user-images.githubusercontent.com/11687090/156850991-33619f36-4e2a-4d18-a742-d7a6d382667d.gif" alt="animated gif of my adobe illustrator script suggestion" width="50%">

To begin with I'm having trouble exporting PNG files from artboards that have many layers each
| example of | my artboards | #=layer amount |
|:--:|:--:|:--:|
| 92 | 56 | 283 |
| 64 | 24 | 5 |
| 310 | 12 | 65 |

The Artboards all have the same canvas size, but the layers are part of a collective.
Some shapes inside the layer-groups are 50x50px, others 350x80px.
I need the exported PNG to have the full transparent canvas size.

As you can see in the video; When I "Generate Asset" before my bad solution, only the shape itself gets exported.

My "hack" (read: hillbilly-solution) is to place a rectangle the size of the artboard on top of the layer with the opacity reduced to 0%.
This works, but the high numbers in the table above are non-fictional (and lacking many artboards)

> After 2 days of searching, this appears to not be natively possible in Illustrator, so a script is needed.

> Thank you for the scripts you shared already. I've been using about a handful quite often

### Please help me. I don't want to copy/paste manually over 2500 times.

**Comment by creold** [comment]
Do you need to export layers into separate png files the size of the parent artboard? If the script adds a rectangle to each layer, it will take you a long time to manually add layers to Assets, right?

**Comment by defactofrank** [comment]
Yes that is correct

Op vr 11 mrt. 2022 09:03 schreef Sergey Osokin ***@***.***>:

**Comment by creold** [comment]
![demo](https://user-images.githubusercontent.com/32217031/158750152-1d0e4585-d8a9-45a6-9757-37c58e349adc.gif)
The simplest version of the script looks like this. I don't know if that's enough.

**Comment by defactofrank** [comment]
This looks absolutely fantastic!

Could this also Generate Multiple Assets if 2 or more layers are selected?

**Comment by creold** [comment]
I would split it into two scripts. One adds rectangles to all document layers. The other finds the object's parent layer and adds the entire layer to the Assets panel.

![2022-03-18 11 48 06](https://user-images.githubusercontent.com/32217031/158951623-74a7fef7-c5bc-4e01-b217-61fca5c1d131.gif)

**Comment by defactofrank** [comment]
Perfect!

**Comment by creold** [comment]
[scripts.zip](https://github.com/creold/illustrator-scripts/files/8302733/scripts.zip)

**Comment by creold** [comment]
There are no simple edits. A different algorithm. In the demo, you have nested layers with name: 0, 1, 2. 
It gets confusing: 
- add rect only to the layers
- only in top-level groups in all layers
- into layers and groups at the same time

**Comment by defactofrank** [comment]
> * only in top-level groups in all layers

Yes. Sorry for the confusion. I've tried to explain it best in detail above

**Comment by creold** [comment]
What should be added to the Assets? Manually selected groups? Not layers.

**Comment by defactofrank** [comment]
When I click on "Generate Multiple Assets", this happens:

![image](https://user-images.githubusercontent.com/11687090/158987882-7a0ed428-5388-4882-9998-2f1228dd6cfa.png)

**Comment by defactofrank** [comment]
When I move the rectangle into the top-level nested group:

![image](https://user-images.githubusercontent.com/11687090/158988250-760fdbf8-5e0f-4cdd-b112-c16f4c54ce4c.png)

That's the goal :D

**Comment by creold** [comment]
> because in your video it does add rectangles to nested groups:

"Bubble" It was a sublayer, not a group.

And if the layer will be single paths without groups?

**Comment by defactofrank** [comment]
You mean like flattening the groups into layers? That's fine too

**Comment by creold** [comment]
No. What about the black rectangle? It is a single path, not in a group.
![Screenshot(16)](https://user-images.githubusercontent.com/32217031/158989577-a00a65b5-ae04-4310-ac53-7bf2789d9f23.png)

**Comment by defactofrank** [comment]
I don't have that many compound layers, maybe 1 in 1000
so that's no issue

**Comment by creold** [comment]
![2022-03-18 16 02 59](https://user-images.githubusercontent.com/32217031/158992125-f4cf6cdc-c761-4def-a5f2-bac5ee2e2d2d.gif)

**Comment by defactofrank** [comment]
Looks fantastic

**Comment by creold** [comment]
[scripts-for-groups.zip](https://github.com/creold/illustrator-scripts/files/8303978/scripts-for-groups.zip)

If you select hundreds or thousands of groups at a time, it will work very slowly. I haven't tested it myself.

**Comment by defactofrank** [comment]
❤️ it!

File size very small too. I am very happy!

**Comment by defactofrank** [comment]
Where can I send a donation?

PayPal is not allowing me to send anything at the time of writing due to political reasons.
Could I interest you in a gift card of any kind?

**Comment by creold** [comment]
I don't think so. Donations are not available to me for an unknown period of time. I just keep posting free scripts for everyone without politics. There is a service for donations in rubles https://donatty.com/sergosokin. But I don't think visa, mastercard or paypal will work there now.

**Comment by defactofrank** [comment]
No worries. I will revisit this at a later date :)

**Comment by defactofrank** [comment]
Hi Sergey,

That looks awesome!
Basically what I had in mind

**Comment by creold** [comment]
@defactofrank oh, it's been so many months. :) By the way, I started an alternative source for donations https://www.buymeacoffee.com/osokin
